name: flutter_request_bloc
description: Package that facilitates REST API calls using flutter_bloc and hydrated_bloc.
version: 1.0.0
homepage: https://github.com/jesusrp98/flutter_request_bloc/

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ">=2.0.0 <3.0.0"
  flutter_bloc: ">=8.0.0 <9.0.0"
  hydrated_bloc: ">=8.0.0 <9.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
