name: flutter_request_bloc
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/jesusrp98/flutter_packages/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ">= 1.0.0 <2.0.0"
  flutter_bloc: ">= 6.0.0 <7.0.0"
  hydrated_bloc: ">= 6.0.0 <7.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  dio: ">= 3.0.0 <4.0.0"
  mockito: ">= 4.0.0 <5.0.0"
  bloc_test: ">= 7.0.0 <8.0.0"

flutter:
